# workflow name
name: First Workflow

# workflow trigger
on: workflow_dispatch

# workflow jobs
jobs:
  first-job:
    # runner / environment
    runs-on: ubuntu-latest
    # steps
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
